### ISSUE TITLE
Fix Gallery 

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/v2-Configurator#10]
We had a working Gallery in:
- Chapter►ViCase►ViCase Size►Gallery

Please bring back its function so it works like before

Also remove the additional Section: Carousel

**Comment by LukasChen** [comment]
Hi Andrew,

You did a great job on the gallery last last night. But Hubert still wants some features, as shown in the picture.

![untitled](https://cloud.githubusercontent.com/assets/10474405/9153625/2dec7406-3e96-11e5-9724-aa4ba54ff625.png)

Hubert wants a 4 preview image in a row below the main image, and when you click it , it slide the main image to the image you click in the preview images. like in any online shop. but, you can slide the preview images as while with the arrows.

Many Thanks,
Lukas Chen

**Comment by LukasChen** [comment]
if you like this video, punch that like button in the face, Like a Boss

**Comment by agbishara** [comment]
Should be fixed now
