### ISSUE TITLE
cost is undiefind

### ISSUE THREAD

**Issue by LukasChen** [V-Squared/v2-Configurator#17]
this happen when you click on a radio button then this error message will be displayed in the debugger

**Comment by agbishara** [comment]
HI Lukas,  What was the section and # or label of the specific Radio.  It seems like maybe the data.json is empty when it should have a cost?  I can code to set it to zero but I need this info to reproduce.  Thanks - Andrew

**Comment by LukasChen** [comment]
hi Andrew,
The bug is on all the radio buttons, when you open debugger and click on any radio button you will get a error message that say "cost is undefined". By the way, if you haven't read my email, can
 you and I debug together at night your time? because I am having some problem that I researched and have no result
![screenshot from 2015-08-03 21 58 17](https://cloud.githubusercontent.com/assets/10474405/9038983/e4011ed8-3a2a-11e5-8bfb-eeffb8682fc7.png)
