### ISSUE TITLE
Radio Button behave weird after I change the ready config

### ISSUE THREAD

**Issue by LukasChen** [V-Squared/v2-Configurator#26]
This is in the feature-newLoad branch, so you need to pull it instead of directly view it on github hosting

I changed the data format of loading "Ready Config" to be the same as cart.json. Now we can create a new ready config by building a config in the configurator and then save it with the "Save my Config" Button in Ready Config. All works, except for:
1. When loading the V2Configurator the Radio Button "High Performance" is selected by default, even it should not be
2. When selecting "Entry Level Performance" I need to select it twice to show the button is selected

**Comment by LukasChen** [comment]
P.S. cart.json is $scope.cart

**Comment by agbishara** [comment]
"yourChoice": [
                    {
                        "name": "Entry Level Performance",
                        "img": "",
                        "for": "Entry",
                        "value": 1    < ---  changed from 0 to 1.

**Comment by LukasChen** [comment]
I implemented the change as you suggested. There was no change in behavior. In other words the buttons still behave wrong. And I do not see how your suggestion is related to the problem. "value" contains the price in USD. All Ready Configs need to have the "value":0 as the Ready Config itself is not adding to total cost.
